spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/minilms
    username: minilms_user
    password: zerobase
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show_sql: true
    
  mail:
    host: smtp.gmail.com
    port: 587
    username: code.kmh9250@gmail.com
    password: bvvisbqmgkcqwhtr
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            
logging:
  level:
    root: info